### ISSUE TITLE
MainActivity에 설명 추가

### ISSUE THREAD

**Issue by okgosu** [naver/naverspeech-sdk-android#2]
3가지 예제상 MainActivity에 아래와 같이 설명 추가 부탁드립니다. 
    // 1. "내 애플리케이션"에서 Client ID를 확인해서 이곳에 적어주세요.
    // 2. build.gradle (Module:app)에서 패키지명을 실제 개발자센터 애플리케이션 설정의 '안드로이드 앱 패키지 이름'으로 바꿔 주세요. 기본 값은 'com.naver.naverspeech.client'으로 되어 있습니다.

대상은 여깁니다.
https://github.com/naver/naverspeech-sdk-android/blob/master/samples/EPDTypeAutoSample/app/src/main/java/com/naver/naverspeech/client/MainActivity.java

**Comment by KwonOhhyeok** [comment]
@okgosu 
설명 추가했습니다. (https://github.com/naver/naverspeech-sdk-android/commit/7a1e11ddd7405978fd2bed2c9a4599c04178dfe0)
