### ISSUE TITLE
mipmap 과 drawable 파일 충돌 해결

### ISSUE THREAD

**Issue by okgosu** [naver/naverspeech-sdk-android#3]
mipmap 과 drawable에 ic_launcher.png가 중복이 되어 있어서, drawable 폴더의 파일은 삭제가 필요합니다.

대상은 여깁니다.

https://github.com/naver/naverspeech-sdk-android/tree/master/samples/EPDTypeAutoSample/app/src/main/res

**Comment by KwonOhhyeok** [comment]
@okgosu 
ic_launcher를 svg로 변경했습니다. 더불어 중복되는 문제도 자연스럽게 해결되었습니다. (https://github.com/naver/naverspeech-sdk-android/commit/8a7f20551d74bb2114cf491c7724bb48d03b4f5e)
